name: Build
on: [ push, pull_request ]
jobs:

  build:
    name: Maven Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: bjhargrave/setup-java@68c162b39ca55fd91a2b77adef09286e7f29b5ab
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      
      - name: Build and deploy with Maven
        if: github.ref == 'refs/heads/main'
        run: mvn -Dstyle.color=always -B -U -P sign deploy
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      
      - name: Build with Maven
        if: github.ref != 'refs/heads/main'
        run: mvn -Dstyle.color=always -B -U verify
